//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniQueue.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniQueue.Tests.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;S:Envelope xmlns:S=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///   &lt;S:Body&gt;
        ///	  &lt;ns2:Get 
        ///		xmlns=&quot;urn://x-artefacts/types/basic/1.1&quot; 
        ///		xmlns:ns2=&quot;urn://x-artefacts/services/message-exchange/types/1.1&quot; 
        ///		xmlns:ns3=&quot;urn://x-artefacts/services/message-exchange/types/faults/1.1&quot;&gt;
        ///		 &lt;ns2:RequestMessage&gt;
        ///			&lt;ns2:Request Id=&quot;SIGNED_BY_USER&quot;&gt;
        ///			   &lt;ns2:SenderProvidedRequestData Id=&quot;SIGNED_BY_CONSUMER&quot;&gt;
        ///				  &lt;ns2:MessageID&gt;0e8cfc01-5e81-11e4-a9ff-d4c9eff07b77&lt;/ns2:MessageID&gt;
        ///				  &lt;MessagePrimaryCont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestXmlMessage {
            get {
                return ResourceManager.GetString("TestXmlMessage", resourceCulture);
            }
        }
    }
}
